/**
 * API Client
 * ==========
 * Axios instance with interceptors for auth token injection and 401 handling.
 * All type definitions for request / response payloads live here.
 *
 * E2E notes:
 *   - Register payload now includes `salt` (generated by keyManager).
 *   - Login response now includes `salt` (server echoes it back).
 *   - Account and Transaction payloads use encrypted_data blobs.
 *   - GET /transactions no longer paginates — it returns the full account
 *     dataset so the client can decrypt and compute balances.
 */

import axios from 'axios'

// ──────────────────────────────────────────────────────────
// Types
// ──────────────────────────────────────────────────────────

export interface LoginRequest {
  email:    string
  password: string
}

export interface RegisterRequest {
  email:           string
  password:        string
  salt:            string  // base64 — generated client-side for PBKDF2
  wrapped_org_key: string  // base64 — wrapped organization key for default org
}

export interface AuthResponse {
  access_token: string
  token_type:   string
  salt?:        string   // returned on login for master-key derivation
}

export interface User {
  id:         string
  email:      string
  created_at: string
}

// ─── Accounts ───────────────────────────────────────────

export interface AccountCreate {
  encrypted_data:     string
  encrypted_dek:      string
  currency?:          string
  encryption_version: number
  organization_id?:   string
}

export interface AccountUpdate {
  encrypted_data?:  string
  organization_id?: string
  wrapped_dek?:     string
  migrated?:        boolean
}

export interface Account {
  id:                 string
  user_id:            string
  organization_id?:   string | null
  encrypted_data:     string | null
  encrypted_dek:      string | null
  currency:           string
  encryption_version: number
  created_at:         string
  updated_at:         string
}

export interface AccountSummary {
  total_credit:  number
  total_debit:   number
  net_balance:   number
  transaction_count: number
}

// ─── Account Backup ──────────────────────────────────────

export interface AccountBackupCreate {
  notes?: string
}

export interface AccountBackupResponse {
  filename:           string
  size_bytes:         number
  transaction_count:  number
  backup_data:        string
  created_at:         string
}

export type RestoreMode = 'replace' | 'merge' | 'new_account'

export interface AccountBackupRestore {
  mode:        RestoreMode
  backup_file: string
}

export interface AccountBackupRestoreResponse {
  status:                 string
  mode:                   string
  restored_transactions:  number
  new_account_id?:        string
  backup_info:            {
    created_at: string
    notes?:     string
  }
}

// ─── Transactions ───────────────────────────────────────

export interface TransactionCreate {
  account_id:         string
  date:               string   // YYYY-MM-DD
  encrypted_data:     string
  encryption_version: number
}

export interface TransactionUpdate {
  date?:            string
  encrypted_data?:  string
}

export interface Transaction {
  id:                 string
  account_id:         string
  date:               string
  encrypted_data:     string | null
  encryption_version: number
  created_at:         string
  updated_at:         string
}

export interface TransactionListResponse {
  transactions: Transaction[]
  total:        number
}

// ─── Organizations ──────────────────────────────────────

export type RoleEnum = 'owner' | 'admin' | 'member' | 'viewer'
export type PermissionEnum = 'full' | 'edit' | 'view'

export interface OrganizationCreate {
  name:            string
  description?:    string
  wrapped_org_key: string
}

export interface OrganizationUpdate {
  name?:        string
  description?: string
  settings?:    Record<string, any>
}

export interface Organization {
  id:              string
  name:            string
  description:     string | null
  role:            RoleEnum
  member_count:    number
  account_count:   number
  created_at:      string
  updated_at:      string
  wrapped_org_key: string
}

export interface OrganizationListItem {
  id:            string
  name:          string
  role:          RoleEnum
  member_count:  number
  account_count: number
  created_at:    string
}

export interface OrganizationMember {
  id:        string
  user_id:   string
  email:     string
  role:      RoleEnum
  joined_at: string
}

export interface MemberRoleUpdate {
  role: RoleEnum
}

export interface TransferOwnership {
  new_owner_id: string
}

export interface AuditLog {
  id:            string
  user_email:    string | null
  action:        string
  resource_type: string | null
  resource_id:   string | null
  details:       Record<string, any>
  ip_address:    string | null
  user_agent:    string | null
  created_at:    string
}

export interface AuditLogList {
  logs:      AuditLog[]
  total:     number
  page:      number
  page_size: number
}

// ─── Key Rotation ───────────────────────────────────────

export interface MemberKeyRotation {
  user_id:         string
  wrapped_org_key: string
}

export interface KeyRotationRequest {
  member_keys:  MemberKeyRotation[]
  account_deks: Record<string, string>  // account_id -> new_wrapped_dek
}

export interface KeyRotationResponse {
  status:           string
  accounts_updated: number
  members_updated:  number
  timestamp:        string
}

// ─── Invitations ────────────────────────────────────────

export interface InvitationCreate {
  email:           string
  role:            RoleEnum
  wrapped_org_key: string
  message?:        string
}

export interface Invitation {
  id:                 string
  organization_id:    string
  organization_name:  string
  email:              string
  role:               RoleEnum
  invited_by_email:   string
  message:            string | null
  token:              string
  wrapped_org_key:    string  // RSA-encrypted org key for E2EE
  expires_at:         string
  created_at:         string
  accepted_at:        string | null
  rejected_at:        string | null
}

// ──────────────────────────────────────────────────────────
// Axios instance
// ──────────────────────────────────────────────────────────

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000'

const apiClient = axios.create({
  baseURL: API_BASE_URL,
  headers: { 'Content-Type': 'application/json' }
})

// Request interceptor — attach Bearer token
apiClient.interceptors.request.use(
  (config) => {
    const token = localStorage.getItem('token')
    if (token) {
      config.headers.Authorization = `Bearer ${token}`
    }
    return config
  },
  (error) => Promise.reject(error)
)

// Response interceptor — clear session on 401
apiClient.interceptors.response.use(
  (response) => response,
  (error) => {
    if (error.response?.status === 401) {
      localStorage.removeItem('token')
      localStorage.removeItem('salt')
      window.location.href = '/login'
    }
    return Promise.reject(error)
  }
)

// ──────────────────────────────────────────────────────────
// API surface
// ──────────────────────────────────────────────────────────

export const authAPI = {
  login:          (data: LoginRequest)   => apiClient.post<AuthResponse>('/api/auth/login',    data),
  register:       (data: RegisterRequest)=> apiClient.post<User>('/api/auth/register', data),
  getCurrentUser: ()                     => apiClient.get<User>('/api/auth/me'),
}

export const accountsAPI = {
  getAll:     ()                                   => apiClient.get<Account[]>('/api/accounts'),
  getById:    (id: string)                         => apiClient.get<Account>(`/api/accounts/${id}`),
  getSummary: (id: string)                         => apiClient.get<AccountSummary>(`/api/accounts/${id}/summary`),
  create:     (data: AccountCreate)                => apiClient.post<Account>('/api/accounts', data),
  update:     (id: string, data: AccountUpdate)    => apiClient.put<Account>(`/api/accounts/${id}`, data),
  delete:     (id: string)                         => apiClient.delete(`/api/accounts/${id}`),

  createBackup: (accountId: string, data: AccountBackupCreate) =>
    apiClient.post<AccountBackupResponse>(`/api/accounts/${accountId}/backup`, data),

  restoreBackup: (accountId: string, mode: RestoreMode, backupFile: string) =>
    apiClient.post<AccountBackupRestoreResponse>(`/api/accounts/${accountId}/restore`, {
      mode,
      backup_file: backupFile
    }),
}

export const transactionsAPI = {
  /**
   * Fetch ALL transactions for an account.
   * Optional date filters are the only server-side filtering available.
   */
  getAll: (params: {
    account_id:  string
    start_date?: string
    end_date?:   string
  }) => apiClient.get<TransactionListResponse>('/api/transactions', { params }),

  getById: (id: string)                            => apiClient.get<Transaction>(`/api/transactions/${id}`),
  create:  (data: TransactionCreate)               => apiClient.post<Transaction>('/api/transactions', data),
  update:  (id: string, data: TransactionUpdate)   => apiClient.put<Transaction>(`/api/transactions/${id}`, data),
  delete:  (id: string)                            => apiClient.delete(`/api/transactions/${id}`),
  restore: (id: string)                            => apiClient.post<Transaction>(`/api/transactions/${id}/restore`),
}

export const organizationsAPI = {
  getAll:     ()                                                  => apiClient.get<OrganizationListItem[]>('/api/organizations'),
  getById:    (id: string)                                        => apiClient.get<Organization>(`/api/organizations/${id}`),
  create:     (data: OrganizationCreate)                          => apiClient.post<Organization>('/api/organizations', data),
  update:     (id: string, data: OrganizationUpdate)              => apiClient.put<Organization>(`/api/organizations/${id}`, data),
  delete:     (id: string)                                        => apiClient.delete(`/api/organizations/${id}`),

  // Member management
  getMembers:     (orgId: string)                                 => apiClient.get<OrganizationMember[]>(`/api/organizations/${orgId}/members`),
  updateMember:   (orgId: string, userId: string, data: MemberRoleUpdate) => apiClient.put<OrganizationMember>(`/api/organizations/${orgId}/members/${userId}`, data),
  removeMember:   (orgId: string, userId: string)                 => apiClient.delete(`/api/organizations/${orgId}/members/${userId}`),
  transferOwnership: (orgId: string, data: TransferOwnership)     => apiClient.post<OrganizationMember>(`/api/organizations/${orgId}/transfer-ownership`, data),

  // Account management
  getAccounts: (orgId: string)                                    => apiClient.get<Account[]>(`/api/organizations/${orgId}/accounts`),

  // Audit logs
  getAuditLogs: (orgId: string, page: number = 1, pageSize: number = 50) =>
    apiClient.get<AuditLogList>(`/api/organizations/${orgId}/audit-logs`, { params: { page, page_size: pageSize } }),

  // Key rotation
  rotateKeys: (orgId: string, data: KeyRotationRequest) =>
    apiClient.post<KeyRotationResponse>(`/api/organizations/${orgId}/rotate-keys`, data),

  // Invitations (org-specific)
  getInvitations: (orgId: string)                                 => apiClient.get<Invitation[]>(`/api/organizations/${orgId}/invitations`),
  createInvitation: (orgId: string, data: InvitationCreate)       => apiClient.post<Invitation>(`/api/organizations/${orgId}/invitations`, data),
  cancelInvitation: (orgId: string, invitationId: string)         => apiClient.delete(`/api/organizations/${orgId}/invitations/${invitationId}`),
}

export const invitationsAPI = {
  getMyInvitations: ()                          => apiClient.get<Invitation[]>('/api/invitations'),
  getByToken:       (token: string)             => apiClient.get<Invitation>(`/api/invitations/${token}`),
  accept:           (token: string, wrapped_org_key: string) => apiClient.post<Invitation>(`/api/invitations/${token}/accept`, { wrapped_org_key }),
  reject:           (token: string)             => apiClient.post<Invitation>(`/api/invitations/${token}/reject`, {}),
}

// System Administration API
export interface SystemStats {
  total_users: number
  total_organizations: number
  total_accounts: number
  total_transactions: number
  active_users_today: number
  active_users_week: number
  active_users_month: number
  database_size_mb: number
  avg_transactions_per_user: number
  avg_accounts_per_org: number
}

export interface UserStats {
  id: string
  email: string
  is_system_admin: boolean
  organization_count: number
  account_count: number
  transaction_count: number
  last_login_at: string | null
  login_count: number
  created_at: string
}

export interface OrganizationStats {
  id: string
  name: string
  member_count: number
  account_count: number
  transaction_count: number
  storage_used_mb: number
  created_at: string
  last_activity: string | null
}

export interface SystemLogEntry {
  id: string
  level: string
  category: string
  message: string
  details: Record<string, any>
  created_at: string
}

export interface SystemLogList {
  logs: SystemLogEntry[]
  total: number
  page: number
  page_size: number
}

export interface SystemSetting {
  id: string
  key: string
  value: string | null
  description: string | null
  updated_at: string
}

export interface BackupMetadata {
  id: string
  backup_file: string
  backup_size: number | null
  backup_type: string | null
  created_at: string
  restored_at: string | null
  notes: string | null
}

export const adminAPI = {
  // Dashboard
  getStats: () => apiClient.get<SystemStats>('/api/admin/stats'),

  // User Management
  getUsers: (page: number = 1, pageSize: number = 50) =>
    apiClient.get<UserStats[]>('/api/admin/users', { params: { page, page_size: pageSize } }),
  toggleSystemAdmin: (userId: string) =>
    apiClient.put(`/api/admin/users/${userId}/admin`),
  deleteUser: (userId: string) =>
    apiClient.delete(`/api/admin/users/${userId}`),

  // Organization Management
  getOrganizations: (page: number = 1, pageSize: number = 50) =>
    apiClient.get<OrganizationStats[]>('/api/admin/organizations', { params: { page, page_size: pageSize } }),

  // System Logs
  getLogs: (level?: string, category?: string, page: number = 1, pageSize: number = 100) =>
    apiClient.get<SystemLogList>('/api/admin/logs', {
      params: { level, category, page, page_size: pageSize }
    }),
  cleanupLogs: (daysOld: number) =>
    apiClient.delete('/api/admin/logs/cleanup', { params: { days_old: daysOld } }),

  // Settings
  getSettings: () => apiClient.get<SystemSetting[]>('/api/admin/settings'),
  updateSetting: (key: string, value: string, description?: string) =>
    apiClient.put(`/api/admin/settings/${key}`, { value, description }),

  // Backups
  createBackup: (notes?: string) => apiClient.post('/api/admin/backup', { notes }),
  listBackups: () => apiClient.get<BackupMetadata[]>('/api/admin/backups'),
  restoreBackup: (backupId: string, confirmation: string) =>
    apiClient.post(`/api/admin/backup/restore/${backupId}`, { confirmation }),
  downloadBackup: (backupId: string) =>
    apiClient.get(`/api/admin/backup/download/${backupId}`, { responseType: 'blob' }),
  getBackupSchedule: () =>
    apiClient.get<{ schedule: string; enabled: boolean; description: string }>('/api/admin/backup/schedule'),
  updateBackupSchedule: (schedule: string, enabled: boolean) =>
    apiClient.put('/api/admin/backup/schedule', { schedule, enabled }),
}

export default apiClient
